'use strict';
const $ = id => document.getElementById(id);
let deck = [], index = 0, score = 0, responses = [], locked = false;
function shuffle(items) { const a = [...items]; for (let i=a.length-1;i>0;i--) { const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function start(focus=true) { deck=shuffle(QUESTIONS).map(q=>({...q,choices:shuffle(q.options.map((text,i)=>({text,correct:i===q.answer})))})); index=0; score=0; responses=[]; $('quiz').hidden=false; $('results').hidden=true; render(focus); }
function updateStats() { $('position').textContent=`Question ${index+1} of ${deck.length}`; $('score').textContent=`${score} correct · ${responses.length} answered`; $('progress').max=deck.length; $('progress').value=responses.length; }
function render(focus=true) { locked=false; const q=deck[index]; updateStats(); $('topic').textContent=q.topic; $('question').textContent=q.question; $('options').replaceChildren(); $('feedback').hidden=true; $('feedback').replaceChildren(); $('next').disabled=true; $('next').textContent=index===deck.length-1?'See results →':'Next question →'; $('answered-note').textContent='Take your time.'; q.choices.forEach((c,i)=>{ const b=document.createElement('button'); b.type='button'; b.className='option'; const letter=document.createElement('span'); letter.className='letter'; letter.textContent='ABCD'[i]; const text=document.createElement('span'); text.className='choice-text'; text.textContent=c.text; b.append(letter,text); b.addEventListener('click',()=>answer(i)); $('options').append(b); }); if(focus) $('question').focus(); }
function answer(i) { if(locked || !Number.isInteger(i) || i<0 || i>3) return; locked=true; const q=deck[index], chosen=q.choices[i], correct=q.choices.find(c=>c.correct); if(chosen.correct) score++; responses.push({q,chosen:chosen.text,correct:chosen.correct}); [...$('options').children].forEach((b,j)=>{ b.disabled=true; if(q.choices[j].correct) b.classList.add('correct'); if(j===i&&!chosen.correct)b.classList.add('wrong'); if(q.choices[j].correct || j===i){ const tag=document.createElement('span');tag.className='choice-state';tag.textContent=q.choices[j].correct?'✓ Correct':'✕ Your choice';b.append(tag); } }); const box=$('feedback');box.className=chosen.correct?'':'incorrect'; const title=document.createElement('strong');title.textContent=chosen.correct?'Correct. Well done.':'Not quite. Here’s why.'; const p=document.createElement('p');p.textContent=(!chosen.correct?`Correct answer: ${correct.text} `:'')+q.explanation; const src=document.createElement('p');src.className='source';src.textContent=q.source;box.append(title,p,src);box.hidden=false;updateStats();$('answered-note').textContent='Answer checked';$('next').disabled=false; }
function next() { if(!locked)return; if(index<deck.length-1){index++;render();}else finish(); }
function finish(){ $('quiz').hidden=true;$('results').hidden=false;$('percentage').textContent=`${Math.round(score/deck.length*100)}%`;$('result-summary').textContent=`${score} of ${deck.length} correct · ${deck.length-score} to review`;$('review').replaceChildren();const missed=responses.filter(r=>!r.correct);const h=document.createElement('h3');h.textContent=missed.length?'Learn from your mistakes':'Every answer correct';$('review').append(h);if(!missed.length){const p=document.createElement('p');p.textContent='Great work. Restart for a fresh order of questions and answers.';$('review').append(p);}missed.forEach(r=>{const d=document.createElement('details'),s=document.createElement('summary');s.textContent=r.q.question;d.append(s);for(const [cls,txt]of [['wrong-text',`Your answer: ${r.chosen}`],['right-text',`Correct answer: ${r.q.choices.find(c=>c.correct).text}`],['',r.q.explanation]]){const p=document.createElement('p');p.className=cls;p.textContent=txt;d.append(p);}const src=document.createElement('small');src.textContent=r.q.source;d.append(src);$('review').append(d);});$('result-heading').focus(); }
$('next').addEventListener('click',next);$('restart').addEventListener('click',()=>start());start(false);
// Optional browser-native agent access; ordinary offline browsers need no support.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_quiz_progress',description:'Read the current quiz progress without changing answers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({answered:responses.length,total:deck.length,score,complete:!$('results').hidden})})).catch(()=>{});}catch{}}
